# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthorAuthorIdGet200ResponseAuthor(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name: str=None, last_name: str=None, books: List[str]=None):
        """AuthorAuthorIdGet200ResponseAuthor - a model defined in OpenAPI

        :param first_name: The first_name of this AuthorAuthorIdGet200ResponseAuthor.
        :param last_name: The last_name of this AuthorAuthorIdGet200ResponseAuthor.
        :param books: The books of this AuthorAuthorIdGet200ResponseAuthor.
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'books': List[str]
        }

        self.attribute_map = {
            'first_name': 'first_name',
            'last_name': 'last_name',
            'books': 'books'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._books = books

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthorAuthorIdGet200ResponseAuthor':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _author__author_id__get_200_response_author of this AuthorAuthorIdGet200ResponseAuthor.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self):
        """Gets the first_name of this AuthorAuthorIdGet200ResponseAuthor.


        :return: The first_name of this AuthorAuthorIdGet200ResponseAuthor.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this AuthorAuthorIdGet200ResponseAuthor.


        :param first_name: The first_name of this AuthorAuthorIdGet200ResponseAuthor.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this AuthorAuthorIdGet200ResponseAuthor.


        :return: The last_name of this AuthorAuthorIdGet200ResponseAuthor.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this AuthorAuthorIdGet200ResponseAuthor.


        :param last_name: The last_name of this AuthorAuthorIdGet200ResponseAuthor.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def books(self):
        """Gets the books of this AuthorAuthorIdGet200ResponseAuthor.


        :return: The books of this AuthorAuthorIdGet200ResponseAuthor.
        :rtype: List[str]
        """
        return self._books

    @books.setter
    def books(self, books):
        """Sets the books of this AuthorAuthorIdGet200ResponseAuthor.


        :param books: The books of this AuthorAuthorIdGet200ResponseAuthor.
        :type books: List[str]
        """

        self._books = books
