# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.author_author_id_get200_response_author import AuthorAuthorIdGet200ResponseAuthor
from openapi_server import util


class AuthorAuthorIdGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, author: AuthorAuthorIdGet200ResponseAuthor=None):
        """AuthorAuthorIdGet200Response - a model defined in OpenAPI

        :param author: The author of this AuthorAuthorIdGet200Response.
        """
        self.openapi_types = {
            'author': AuthorAuthorIdGet200ResponseAuthor
        }

        self.attribute_map = {
            'author': 'author'
        }

        self._author = author

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthorAuthorIdGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _author__author_id__get_200_response of this AuthorAuthorIdGet200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def author(self):
        """Gets the author of this AuthorAuthorIdGet200Response.


        :return: The author of this AuthorAuthorIdGet200Response.
        :rtype: AuthorAuthorIdGet200ResponseAuthor
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this AuthorAuthorIdGet200Response.


        :param author: The author of this AuthorAuthorIdGet200Response.
        :type author: AuthorAuthorIdGet200ResponseAuthor
        """

        self._author = author
