# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.book_book_id_get200_response_book import BookBookIdGet200ResponseBook
from openapi_server import util


class BookBookIdGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book: BookBookIdGet200ResponseBook=None):
        """BookBookIdGet200Response - a model defined in OpenAPI

        :param book: The book of this BookBookIdGet200Response.
        """
        self.openapi_types = {
            'book': BookBookIdGet200ResponseBook
        }

        self.attribute_map = {
            'book': 'book'
        }

        self._book = book

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BookBookIdGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _book__book_id__get_200_response of this BookBookIdGet200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book(self):
        """Gets the book of this BookBookIdGet200Response.


        :return: The book of this BookBookIdGet200Response.
        :rtype: BookBookIdGet200ResponseBook
        """
        return self._book

    @book.setter
    def book(self, book):
        """Sets the book of this BookBookIdGet200Response.


        :param book: The book of this BookBookIdGet200Response.
        :type book: BookBookIdGet200ResponseBook
        """

        self._book = book
