# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class BookBookIdGet200ResponseBook(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, title: str=None, author: str=None):
        """BookBookIdGet200ResponseBook - a model defined in OpenAPI

        :param id: The id of this BookBookIdGet200ResponseBook.
        :param title: The title of this BookBookIdGet200ResponseBook.
        :param author: The author of this BookBookIdGet200ResponseBook.
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'author': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author'
        }

        self._id = id
        self._title = title
        self._author = author

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BookBookIdGet200ResponseBook':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _book__book_id__get_200_response_book of this BookBookIdGet200ResponseBook.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this BookBookIdGet200ResponseBook.


        :return: The id of this BookBookIdGet200ResponseBook.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BookBookIdGet200ResponseBook.


        :param id: The id of this BookBookIdGet200ResponseBook.
        :type id: int
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this BookBookIdGet200ResponseBook.


        :return: The title of this BookBookIdGet200ResponseBook.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BookBookIdGet200ResponseBook.


        :param title: The title of this BookBookIdGet200ResponseBook.
        :type title: str
        """

        self._title = title

    @property
    def author(self):
        """Gets the author of this BookBookIdGet200ResponseBook.


        :return: The author of this BookBookIdGet200ResponseBook.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this BookBookIdGet200ResponseBook.


        :param author: The author of this BookBookIdGet200ResponseBook.
        :type author: str
        """

        self._author = author
