# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class BookPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title: str=None, author: int=None):
        """BookPostRequest - a model defined in OpenAPI

        :param title: The title of this BookPostRequest.
        :param author: The author of this BookPostRequest.
        """
        self.openapi_types = {
            'title': str,
            'author': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author'
        }

        self._title = title
        self._author = author

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BookPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _book_post_request of this BookPostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this BookPostRequest.


        :return: The title of this BookPostRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BookPostRequest.


        :param title: The title of this BookPostRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def author(self):
        """Gets the author of this BookPostRequest.


        :return: The author of this BookPostRequest.
        :rtype: int
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this BookPostRequest.


        :param author: The author of this BookPostRequest.
        :type author: int
        """

        self._author = author
